name: student
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  get_it: 7.2.0
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  
  image_picker: ^0.8.7+5
  injectable: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

  injectable_generator: ^1.2.2

flutter:
  uses-material-design: true


  assets:
   - assets/default_image.png
